//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteamVR_OculusDash_Switcher.Properties.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizationStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizationStrings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SteamVR_OculusDash_Switcher.Properties.Localization.LocalizationStrings", typeof(LocalizationStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close.
        /// </summary>
        internal static string Button__Close {
            get {
                return ResourceManager.GetString("Button__Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Continue.
        /// </summary>
        internal static string Button__Continue {
            get {
                return ResourceManager.GetString("Button__Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exit.
        /// </summary>
        internal static string Button__Exit {
            get {
                return ResourceManager.GetString("Button__Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Apply.
        /// </summary>
        internal static string Button_Apply {
            get {
                return ResourceManager.GetString("Button_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на One click mode control tips.
        /// </summary>
        internal static string ControlsTipsForm__TitleText {
            get {
                return ResourceManager.GetString("ControlsTipsForm__TitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Switch SteamVR ↔ Oculus.
        /// </summary>
        internal static string ControlsTipsForm_tip__LMB {
            get {
                return ResourceManager.GetString("ControlsTipsForm_tip__LMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Kill SteamVR.
        /// </summary>
        internal static string ControlsTipsForm_tip__MMB {
            get {
                return ResourceManager.GetString("ControlsTipsForm_tip__MMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open context menu.
        /// </summary>
        internal static string ControlsTipsForm_tip__RMB {
            get {
                return ResourceManager.GetString("ControlsTipsForm_tip__RMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Minimalistic shit.
        /// </summary>
        internal static string IconRealismLevel_0_Discription {
            get {
                return ResourceManager.GetString("IconRealismLevel_0_Discription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Colorful minimalistic shit.
        /// </summary>
        internal static string IconRealismLevel_1_Discription {
            get {
                return ResourceManager.GetString("IconRealismLevel_1_Discription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Realistic icons.
        /// </summary>
        internal static string IconRealismLevel_2_Discription {
            get {
                return ResourceManager.GetString("IconRealismLevel_2_Discription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yes, I know what &quot;icon&quot; means. 
        /// It&apos;s a photo, but transparent.
        /// </summary>
        internal static string IconRealismLevel_3_Discription {
            get {
                return ResourceManager.GetString("IconRealismLevel_3_Discription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на I don&apos;t know how did you set the impossible value.
        /// </summary>
        internal static string IconRealismLevel_Unknown_Discription {
            get {
                return ResourceManager.GetString("IconRealismLevel_Unknown_Discription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Break SteamVR.
        /// </summary>
        internal static string MenuOptions__Break_SteamVR {
            get {
                return ResourceManager.GetString("MenuOptions__Break_SteamVR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Control tips.
        /// </summary>
        internal static string MenuOptions__Control_tips {
            get {
                return ResourceManager.GetString("MenuOptions__Control_tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enable one-click mode.
        /// </summary>
        internal static string MenuOptions__Enable_one_click_mode {
            get {
                return ResourceManager.GetString("MenuOptions__Enable_one_click_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Kill SteamVR.
        /// </summary>
        internal static string MenuOptions__Kill_SteamVR {
            get {
                return ResourceManager.GetString("MenuOptions__Kill_SteamVR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Launch with Windows.
        /// </summary>
        internal static string MenuOptions__Launch_with_Windows {
            get {
                return ResourceManager.GetString("MenuOptions__Launch_with_Windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на More settings.
        /// </summary>
        internal static string MenuOptions__More_Settings {
            get {
                return ResourceManager.GetString("MenuOptions__More_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Restore SteamVR.
        /// </summary>
        internal static string MenuOptions__Restore_SteamVR {
            get {
                return ResourceManager.GetString("MenuOptions__Restore_SteamVR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на → Oculus.
        /// </summary>
        internal static string MenuOptions__Switch_to_Oculus {
            get {
                return ResourceManager.GetString("MenuOptions__Switch_to_Oculus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на → SteamVR.
        /// </summary>
        internal static string MenuOptions__Switch_to_SteamVR {
            get {
                return ResourceManager.GetString("MenuOptions__Switch_to_SteamVR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error while changing Autorun value.
        /// </summary>
        internal static string MenuOptions_SetAutorunValue_ErrorText {
            get {
                return ResourceManager.GetString("MenuOptions_SetAutorunValue_ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SteamVR not found! The program will not work if you continue.
        /// </summary>
        internal static string MessageBox_text__SteamVR_not_found {
            get {
                return ResourceManager.GetString("MessageBox_text__SteamVR_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        internal static string MessageBox_Title__Error {
            get {
                return ResourceManager.GetString("MessageBox_Title__Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select Oculus folder path.
        /// </summary>
        internal static string OculusDash_OculusNotFound__Select_Oculus_folder_path {
            get {
                return ResourceManager.GetString("OculusDash_OculusNotFound__Select_Oculus_folder_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Newest Oculus Killer was downloaded successfully.
        /// </summary>
        internal static string OculusKiller_StatusDiscription_Downloaded {
            get {
                return ResourceManager.GetString("OculusKiller_StatusDiscription_Downloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You are already have the lastest version.
        /// </summary>
        internal static string OculusKiller_StatusDiscription_NoAction {
            get {
                return ResourceManager.GetString("OculusKiller_StatusDiscription_NoAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Oculus Killer was updated successfully.
        /// </summary>
        internal static string OculusKiller_StatusDiscription_Updated {
            get {
                return ResourceManager.GetString("OculusKiller_StatusDiscription_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Interface.
        /// </summary>
        internal static string SettingsForm__Interface {
            get {
                return ResourceManager.GetString("SettingsForm__Interface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на General functions.
        /// </summary>
        internal static string SettingsForm__Main_functions {
            get {
                return ResourceManager.GetString("SettingsForm__Main_functions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Saved!.
        /// </summary>
        internal static string SettingsForm_btnApply_label__Saved {
            get {
                return ResourceManager.GetString("SettingsForm_btnApply_label__Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Check Oculus Killer updates.
        /// </summary>
        internal static string SettingsForm_btnCheckOculusKillerUpdates {
            get {
                return ResourceManager.GetString("SettingsForm_btnCheckOculusKillerUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Checking updates....
        /// </summary>
        internal static string SettingsForm_btnCheckOculusKillerUpdates__Checking_updates {
            get {
                return ResourceManager.GetString("SettingsForm_btnCheckOculusKillerUpdates__Checking_updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на show &quot;R3pl@ceMe&quot; option.
        /// </summary>
        internal static string SettingsForm_cb__show_xxx_option {
            get {
                return ResourceManager.GetString("SettingsForm_cb__show_xxx_option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Kill Oculus Dash.
        /// </summary>
        internal static string SettingsForm_cbKillOculus {
            get {
                return ResourceManager.GetString("SettingsForm_cbKillOculus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stop playing amazing song?.
        /// </summary>
        internal static string SettingsForm_EasterEgg_OnClosing_Message__Stop_playing_amazing_music {
            get {
                return ResourceManager.GetString("SettingsForm_EasterEgg_OnClosing_Message__Stop_playing_amazing_music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Easteregg speacking with you.
        /// </summary>
        internal static string SettingsForm_EasterEgg_OnClosing_Title__Easter_egg_speaking_with_you {
            get {
                return ResourceManager.GetString("SettingsForm_EasterEgg_OnClosing_Title__Easter_egg_speaking_with_you", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Icons realism level.
        /// </summary>
        internal static string SettingsForm_lbIconsRealism {
            get {
                return ResourceManager.GetString("SettingsForm_lbIconsRealism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language.
        /// </summary>
        internal static string SettingsForm_lbLanguage {
            get {
                return ResourceManager.GetString("SettingsForm_lbLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SteamVR disable method.
        /// </summary>
        internal static string SettingsForm_lbSteamVRDisableMethod {
            get {
                return ResourceManager.GetString("SettingsForm_lbSteamVRDisableMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tray icon color:.
        /// </summary>
        internal static string SettingsForm_lbTrayIconColor {
            get {
                return ResourceManager.GetString("SettingsForm_lbTrayIconColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Black.
        /// </summary>
        internal static string SettingsForm_lbTrayIconColorValue_Black {
            get {
                return ResourceManager.GetString("SettingsForm_lbTrayIconColorValue_Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на White.
        /// </summary>
        internal static string SettingsForm_lbTrayIconColorValue_White {
            get {
                return ResourceManager.GetString("SettingsForm_lbTrayIconColorValue_White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Can&apos;t play amazing song.
        /// </summary>
        internal static string SettingsForm_RealismLevel_Max_Error {
            get {
                return ResourceManager.GetString("SettingsForm_RealismLevel_Max_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        internal static string SettingsForm_Title {
            get {
                return ResourceManager.GetString("SettingsForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на both original file and renamed file not found.
        /// </summary>
        internal static string SteamVRDisable_IsMethodApplied_RenameExe_Exception__both_original_and_renamed_file_not_found {
            get {
                return ResourceManager.GetString("SteamVRDisable_IsMethodApplied_RenameExe_Exception__both_original_and_renamed_fil" +
                        "e_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Replace SteamVR exes with empty ones.
        /// </summary>
        internal static string SteamVRDisableMethod_Discription__DummyExe {
            get {
                return ResourceManager.GetString("SteamVRDisableMethod_Discription__DummyExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Do nothing.
        /// </summary>
        internal static string SteamVRDisableMethod_Discription__None {
            get {
                return ResourceManager.GetString("SteamVRDisableMethod_Discription__None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rename SteamVR .exe files.
        /// </summary>
        internal static string SteamVRDisableMethod_Discription__RenameExe {
            get {
                return ResourceManager.GetString("SteamVRDisableMethod_Discription__RenameExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rename SteamVR Folder.
        /// </summary>
        internal static string SteamVRDisableMethod_Discription__RenameFolder {
            get {
                return ResourceManager.GetString("SteamVRDisableMethod_Discription__RenameFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dummy exe.
        /// </summary>
        internal static string SteamVRDisableMethod_ToString__DummyExe {
            get {
                return ResourceManager.GetString("SteamVRDisableMethod_ToString__DummyExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на None.
        /// </summary>
        internal static string SteamVRDisableMethod_ToString__None {
            get {
                return ResourceManager.GetString("SteamVRDisableMethod_ToString__None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rename exe.
        /// </summary>
        internal static string SteamVRDisableMethod_ToString__Renameexe {
            get {
                return ResourceManager.GetString("SteamVRDisableMethod_ToString__Renameexe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rename folder.
        /// </summary>
        internal static string SteamVRDisableMethod_ToString__RenameFolder {
            get {
                return ResourceManager.GetString("SteamVRDisableMethod_ToString__RenameFolder", resourceCulture);
            }
        }
    }
}
