//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteamVR_OculusDash_Switcher.Properties.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizationStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizationStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SteamVR_OculusDash_Switcher.Properties.Localization.LocalizationStrings", typeof(LocalizationStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Button__Close {
            get {
                return ResourceManager.GetString("Button__Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Button__Continue {
            get {
                return ResourceManager.GetString("Button__Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Button__Exit {
            get {
                return ResourceManager.GetString("Button__Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string Button_Apply {
            get {
                return ResourceManager.GetString("Button_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        internal static string Button_cancel {
            get {
                return ResourceManager.GetString("Button_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to skip (SteamVR is considered restored).
        /// </summary>
        internal static string Button_skip {
            get {
                return ResourceManager.GetString("Button_skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One click mode control tips.
        /// </summary>
        internal static string ControlsTipsForm__TitleText {
            get {
                return ResourceManager.GetString("ControlsTipsForm__TitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch SteamVR ↔ Oculus.
        /// </summary>
        internal static string ControlsTipsForm_tip__LMB {
            get {
                return ResourceManager.GetString("ControlsTipsForm_tip__LMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill SteamVR.
        /// </summary>
        internal static string ControlsTipsForm_tip__MMB {
            get {
                return ResourceManager.GetString("ControlsTipsForm_tip__MMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open context menu.
        /// </summary>
        internal static string ControlsTipsForm_tip__RMB {
            get {
                return ResourceManager.GetString("ControlsTipsForm_tip__RMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimalistic shit.
        /// </summary>
        internal static string IconRealismLevel_0_Discription {
            get {
                return ResourceManager.GetString("IconRealismLevel_0_Discription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colorful minimalistic shit.
        /// </summary>
        internal static string IconRealismLevel_1_Discription {
            get {
                return ResourceManager.GetString("IconRealismLevel_1_Discription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realistic icons.
        /// </summary>
        internal static string IconRealismLevel_2_Discription {
            get {
                return ResourceManager.GetString("IconRealismLevel_2_Discription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, I know what &quot;icon&quot; means. 
        /// It&apos;s a photo, but transparent.
        /// </summary>
        internal static string IconRealismLevel_3_Discription {
            get {
                return ResourceManager.GetString("IconRealismLevel_3_Discription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t know how did you set the impossible value.
        /// </summary>
        internal static string IconRealismLevel_Unknown_Discription {
            get {
                return ResourceManager.GetString("IconRealismLevel_Unknown_Discription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break SteamVR.
        /// </summary>
        internal static string MenuOptions__Break_SteamVR {
            get {
                return ResourceManager.GetString("MenuOptions__Break_SteamVR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control tips.
        /// </summary>
        internal static string MenuOptions__Control_tips {
            get {
                return ResourceManager.GetString("MenuOptions__Control_tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable one-click mode.
        /// </summary>
        internal static string MenuOptions__Enable_one_click_mode {
            get {
                return ResourceManager.GetString("MenuOptions__Enable_one_click_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill SteamVR.
        /// </summary>
        internal static string MenuOptions__Kill_SteamVR {
            get {
                return ResourceManager.GetString("MenuOptions__Kill_SteamVR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch with Windows.
        /// </summary>
        internal static string MenuOptions__Launch_with_Windows {
            get {
                return ResourceManager.GetString("MenuOptions__Launch_with_Windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More settings.
        /// </summary>
        internal static string MenuOptions__More_Settings {
            get {
                return ResourceManager.GetString("MenuOptions__More_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore SteamVR.
        /// </summary>
        internal static string MenuOptions__Restore_SteamVR {
            get {
                return ResourceManager.GetString("MenuOptions__Restore_SteamVR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to → Oculus.
        /// </summary>
        internal static string MenuOptions__Switch_to_Oculus {
            get {
                return ResourceManager.GetString("MenuOptions__Switch_to_Oculus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to → SteamVR.
        /// </summary>
        internal static string MenuOptions__Switch_to_SteamVR {
            get {
                return ResourceManager.GetString("MenuOptions__Switch_to_SteamVR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while changing Autorun value.
        /// </summary>
        internal static string MenuOptions_SetAutorunValue_ErrorText {
            get {
                return ResourceManager.GetString("MenuOptions_SetAutorunValue_ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SteamVR not found! The program will not work if you continue.
        /// </summary>
        internal static string MessageBox_text__SteamVR_not_found {
            get {
                return ResourceManager.GetString("MessageBox_text__SteamVR_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MessageBox_Title__Error {
            get {
                return ResourceManager.GetString("MessageBox_Title__Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Oculus folder path.
        /// </summary>
        internal static string OculusDash_OculusNotFound__Select_Oculus_folder_path {
            get {
                return ResourceManager.GetString("OculusDash_OculusNotFound__Select_Oculus_folder_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newest Oculus Killer was downloaded successfully.
        /// </summary>
        internal static string OculusKiller_StatusDiscription_Downloaded {
            get {
                return ResourceManager.GetString("OculusKiller_StatusDiscription_Downloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already have the lastest version.
        /// </summary>
        internal static string OculusKiller_StatusDiscription_NoAction {
            get {
                return ResourceManager.GetString("OculusKiller_StatusDiscription_NoAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oculus Killer was updated successfully.
        /// </summary>
        internal static string OculusKiller_StatusDiscription_Updated {
            get {
                return ResourceManager.GetString("OculusKiller_StatusDiscription_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface.
        /// </summary>
        internal static string SettingsForm__Interface {
            get {
                return ResourceManager.GetString("SettingsForm__Interface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General functions.
        /// </summary>
        internal static string SettingsForm__Main_functions {
            get {
                return ResourceManager.GetString("SettingsForm__Main_functions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved!.
        /// </summary>
        internal static string SettingsForm_btnApply_label__Saved {
            get {
                return ResourceManager.GetString("SettingsForm_btnApply_label__Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Oculus Killer updates.
        /// </summary>
        internal static string SettingsForm_btnCheckOculusKillerUpdates {
            get {
                return ResourceManager.GetString("SettingsForm_btnCheckOculusKillerUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking updates....
        /// </summary>
        internal static string SettingsForm_btnCheckOculusKillerUpdates__Checking_updates {
            get {
                return ResourceManager.GetString("SettingsForm_btnCheckOculusKillerUpdates__Checking_updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show &quot;R3pl@ceMe&quot; option.
        /// </summary>
        internal static string SettingsForm_cb__show_xxx_option {
            get {
                return ResourceManager.GetString("SettingsForm_cb__show_xxx_option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill Oculus Dash.
        /// </summary>
        internal static string SettingsForm_cbKillOculus {
            get {
                return ResourceManager.GetString("SettingsForm_cbKillOculus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop playing amazing song?.
        /// </summary>
        internal static string SettingsForm_EasterEgg_OnClosing_Message__Stop_playing_amazing_music {
            get {
                return ResourceManager.GetString("SettingsForm_EasterEgg_OnClosing_Message__Stop_playing_amazing_music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easteregg speacking with you.
        /// </summary>
        internal static string SettingsForm_EasterEgg_OnClosing_Title__Easter_egg_speaking_with_you {
            get {
                return ResourceManager.GetString("SettingsForm_EasterEgg_OnClosing_Title__Easter_egg_speaking_with_you", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icons realism level.
        /// </summary>
        internal static string SettingsForm_lbIconsRealism {
            get {
                return ResourceManager.GetString("SettingsForm_lbIconsRealism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string SettingsForm_lbLanguage {
            get {
                return ResourceManager.GetString("SettingsForm_lbLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SteamVR disable method.
        /// </summary>
        internal static string SettingsForm_lbSteamVRDisableMethod {
            get {
                return ResourceManager.GetString("SettingsForm_lbSteamVRDisableMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tray icon color:.
        /// </summary>
        internal static string SettingsForm_lbTrayIconColor {
            get {
                return ResourceManager.GetString("SettingsForm_lbTrayIconColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        internal static string SettingsForm_lbTrayIconColorValue_Black {
            get {
                return ResourceManager.GetString("SettingsForm_lbTrayIconColorValue_Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        internal static string SettingsForm_lbTrayIconColorValue_White {
            get {
                return ResourceManager.GetString("SettingsForm_lbTrayIconColorValue_White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t play amazing song.
        /// </summary>
        internal static string SettingsForm_RealismLevel_Max_Error {
            get {
                return ResourceManager.GetString("SettingsForm_RealismLevel_Max_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsForm_Title {
            get {
                return ResourceManager.GetString("SettingsForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both SteamVR and SteamVR_ (backup) exist and not empty.
        /// </summary>
        internal static string SteamVR_Restore_RenameFolder_Error_BothFoldersExist_Content {
            get {
                return ResourceManager.GetString("SteamVR_Restore_RenameFolder_Error_BothFoldersExist_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete &quot;SteamVR_&quot; (reccomended).
        /// </summary>
        internal static string SteamVR_Restore_RenameFolder_Error_BothFoldersExist_DeleteBackup {
            get {
                return ResourceManager.GetString("SteamVR_Restore_RenameFolder_Error_BothFoldersExist_DeleteBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace SteamVR with backup (default).
        /// </summary>
        internal static string SteamVR_Restore_RenameFolder_Error_BothFoldersExist_Option_Replace {
            get {
                return ResourceManager.GetString("SteamVR_Restore_RenameFolder_Error_BothFoldersExist_Option_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something wrong happened and SteamVR become unrecoverable broken 😭 (SteamVR and its backup not found).
        /// </summary>
        internal static string SteamVR_Restore_RenameFolder_Error_NoBackup {
            get {
                return ResourceManager.GetString("SteamVR_Restore_RenameFolder_Error_NoBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to both original file and renamed file not found.
        /// </summary>
        internal static string SteamVRDisable_IsMethodApplied_RenameExe_Exception__both_original_and_renamed_file_not_found {
            get {
                return ResourceManager.GetString("SteamVRDisable_IsMethodApplied_RenameExe_Exception__both_original_and_renamed_fil" +
                        "e_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace SteamVR exes with empty ones.
        /// </summary>
        internal static string SteamVRDisableMethod_Discription__DummyExe {
            get {
                return ResourceManager.GetString("SteamVRDisableMethod_Discription__DummyExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do nothing.
        /// </summary>
        internal static string SteamVRDisableMethod_Discription__None {
            get {
                return ResourceManager.GetString("SteamVRDisableMethod_Discription__None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename SteamVR .exe files.
        /// </summary>
        internal static string SteamVRDisableMethod_Discription__RenameExe {
            get {
                return ResourceManager.GetString("SteamVRDisableMethod_Discription__RenameExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename SteamVR Folder.
        /// </summary>
        internal static string SteamVRDisableMethod_Discription__RenameFolder {
            get {
                return ResourceManager.GetString("SteamVRDisableMethod_Discription__RenameFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dummy exe.
        /// </summary>
        internal static string SteamVRDisableMethod_ToString__DummyExe {
            get {
                return ResourceManager.GetString("SteamVRDisableMethod_ToString__DummyExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string SteamVRDisableMethod_ToString__None {
            get {
                return ResourceManager.GetString("SteamVRDisableMethod_ToString__None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename exe.
        /// </summary>
        internal static string SteamVRDisableMethod_ToString__Renameexe {
            get {
                return ResourceManager.GetString("SteamVRDisableMethod_ToString__Renameexe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename folder.
        /// </summary>
        internal static string SteamVRDisableMethod_ToString__RenameFolder {
            get {
                return ResourceManager.GetString("SteamVRDisableMethod_ToString__RenameFolder", resourceCulture);
            }
        }
    }
}
